MobilyaProje/Controllers/KPanelController.cs
using MobilyaProje.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace MobilyaProje.Controllers
{
    [Authorize]
    public class KPanelController : Controller
    {
        Context dr = new Context();
        // GET: KPanel
        public ActionResult Index()
        {
            var mail = (string)Session["Kullanici"];

            var adsoyad = dr.Admins.Where(x => x.Kullanici == mail).Select(k => k.AdSoyad).FirstOrDefault();
            ViewBag.adsoyad = adsoyad;



            var is2 = dr.Hizmetlers.Count().ToString();
            ViewBag.d2 = is2;

            var is3 = dr.MusteriYorums.Count().ToString();
            ViewBag.d3 = is3;

            var is4 = dr.Bloks.Count().ToString();
            ViewBag.d4 = is4;

            var is5 = dr.Mesajs.Count().ToString();
            ViewBag.d5 = is5;


            return View();
        }

        ///-----------------------------------------------------------------
        ///--------------------------------------------------Kullanıcı Güncelle Ekle Sil 
        ///
        ///-----------
        ///
        public ActionResult Adminkullanici()
        {
            //var value = dr.Bloglar.Where(d => d.Durum == true).ToList();
            var value33 = dr.Admins.ToList();

            return View(value33);
        }



        ///// Ekle
        ///

        [HttpGet]
        public ActionResult AdminKulEkle()
        {

            return View();
        }


        // Veriler geldiginde HttpPost çalışır
        [HttpPost]
        public ActionResult AdminKulEkle(Admin u)
        {
            //if (ModelState.IsValid)
            //{
            //}

            dr.Admins.Add(u);
            dr.SaveChanges();
            return RedirectToAction("Adminkullanici");

            //return View();
        }

        ////  Sil
        ///
        public ActionResult AdminKulSil(int id)
        {
            var urnsil = dr.Admins.Find(id);
            dr.Admins.Remove(urnsil);
            dr.SaveChanges();
            return RedirectToAction("Adminkullanici");
        }


        // Getir

        public ActionResult AdminKulGetr(int id)
        {

            var urngetr = dr.Admins.Find(id);
            return View("AdminKulGetr", urngetr);
        }

        // Güncellle

        public ActionResult AdmKulGuncelle(Admin u)
        {

            var value = dr.Admins.Find(u.id);
            value.Kullanici = u.Kullanici;
            value.Sifre = u.Sifre;
            value.AdSoyad = u.AdSoyad;

            //value.AdminYetki.id = u.id;
            dr.SaveChanges();
            return RedirectToAction("Adminkullanici");
        }














        ///////////////////////////////---------------------------------------------- Ana sayfa Bilgi Ekle Güncelle Sil
        ///

        public ActionResult AdmAnaSayfaBilgi()
        {
            var value33 = dr.AnaSayfas.OrderByDescending(l => l.id).ToList();

            //var value = dr.Hizmetler.Where(d => d.Durum == true).ToList();
            return View(value33);
        }



        // Getir

        public ActionResult AdmAnaSayfaBilgiGetir(int id)
        {


            var urngetr = dr.AnaSayfas.Find(id);
            return View("AdmAnaSayfaBilgiGetir", urngetr);
        }

        // Güncellle

        public ActionResult AdmAnaSayfaBilgiGuncel(AnaSayfa u, HttpPostedFileBase File, HttpPostedFileBase File1, HttpPostedFileBase File2)
        {



            if (File != null)
            {
                FileInfo fileinfo = new FileInfo(File.FileName);
                WebImage img = new WebImage(File.InputStream);
                string uzanti = (Guid.NewGuid().ToString() + fileinfo.Extension).ToLower();
                //img.Resize(225, 180, false, false);
                string tamyol = "~/Resim/" + uzanti;
                img.Save(Server.MapPath(tamyol));
                u.Banner = "/Resim/" + uzanti;

            }


            if (File1 != null)
            {
                FileInfo fileinfo = new FileInfo(File1.FileName);
                WebImage img = new WebImage(File1.InputStream);
                string uzanti = (Guid.NewGuid().ToString() + fileinfo.Extension).ToLower();
                //img.Resize(225, 180, false, false);
                string tamyol = "~/Resim/" + uzanti;
                img.Save(Server.MapPath(tamyol));
                u.Banner1 = "/Resim/" + uzanti;

            }


            if (File2 != null)
            {
                FileInfo fileinfo = new FileInfo(File2.FileName);
                WebImage img = new WebImage(File2.InputStream);
                string uzanti = (Guid.NewGuid().ToString() + fileinfo.Extension).ToLower();
                //img.Resize(225, 180, false, false);
                string tamyol = "~/Resim/" + uzanti;
                img.Save(Server.MapPath(tamyol));
                u.Banner2 = "/Resim/" + uzanti;

            }






            var value = dr.AnaSayfas.Find(u.id);
            if (u.Banner != null)
            {
                value.Banner = u.Banner;
            }

            if (u.Banner1 != null)
            {
                value.Banner1 = u.Banner1;
            }

            if (u.Banner2 != null)
            {
                value.Banner2 = u.Banner2;
            }

            value.SloganKucuk = u.SloganKucuk;
            value.SloganKucuk1 = u.SloganKucuk1;
            value.SloganKucuk2 = u.SloganKucuk2;

            value.SloganBuyuk = u.SloganBuyuk;
            value.SloganBuyuk1 = u.SloganBuyuk1;
            value.SloganBuyuk2 = u.SloganBuyuk2;

            value.NeYapiyoruzBaslik = u.NeYapiyoruzBaslik;
            value.SurecimizBaslik = u.SurecimizBaslik;
            value.YorumBalik = u.YorumBalik;
            dr.SaveChanges();
            return RedirectToAction("AdmAnaSayfaBilgi");

        }










        // Bloglar 

        public ActionResult AdminBlog()
        {
            var value = dr.Bloks.OrderByDescending(l => l.id).ToList();
            return View(value);
        }


        [HttpGet]
        public ActionResult AdminBEkle()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AdminBEkle(Blok b, HttpPostedFileBase File)
        {
            if (File != null)
            {
                FileInfo fileinfo = new FileInfo(File.FileName);
                WebImage img = new WebImage(File.InputStream);
                string uzanti = (Guid.NewGuid().ToString() + fileinfo.Extension).ToLower();
                //img.Resize(225, 180, false, false);
                string tamyol = "~/Resim/" + uzanti;
                img.Save(Server.MapPath(tamyol));
                b.Resim = "/Resim/" + uzanti;

            }

            dr.Bloks.Add(b);
            dr.SaveChanges();
            return RedirectToAction("AdminBlog");
        }

        // Blog Sil
        public ActionResult AdminBSil(int id)
        {
            var blgsil = dr.Bloks.Find(id);
            dr.Bloks.Remove(blgsil);
            dr.SaveChanges();
            return RedirectToAction("AdminBlog");
        }

        // Blog Getir

        public ActionResult AdminBGetir(int id)
        {
            var blggetr = dr.Bloks.Find(id);
            return View("AdminBGetir", blggetr);
        }


        // Blog Güncelle

        public ActionResult UrunGuncelle(Blok b, HttpPostedFileBase File)
        {

            if (File != null)
            {
                FileInfo fileinfo = new FileInfo(File.FileName);
                WebImage img = new WebImage(File.InputStream);
                string uzanti = (Guid.NewGuid().ToString() + fileinfo.Extension).ToLower();
                //img.Resize(225, 180, false, false);
                string tamyol = "~/Resim/" + uzanti;
                img.Save(Server.MapPath(tamyol));
                b.Resim = "/Resim/" + uzanti;

            }


            var deger = dr.Bloks.Find(b.id);

            deger.Baslik = b.Baslik;
            deger.icerik = b.icerik;
            deger.icerik1 = b.icerik1;
            deger.icerik2 = b.icerik2;
            if (b.Resim != null)
            {
                deger.Resim = b.Resim;
            }
            deger.Gun = b.Gun;
            deger.Ay = b.Ay;

            dr.SaveChanges();
            return RedirectToAction("AdminBlog");

        }









        /// blog Sayfası   Resimli Kısmı
        /// 

        public ActionResult AdmBlogBannerResim()
        {
            var de = dr.BlokSayfas.ToList();
            return View(de);
        }



        // Bilgi getir
        public ActionResult AdmBlogBannerResimGetir(int id)
        {
            var degerler = dr.BlokSayfas.Find(id);
            return View("AdmBlogBannerResimGetir", degerler);
        }


        // Blog Güncelle

        public ActionResult AdmBlogBannerResimGuncelle(BlokSayfa b, HttpPostedFileBase File)
        {
            if (File != null)
            {
                FileInfo fileinfo = new FileInfo(File.FileName);
                WebImage img = new WebImage(File.InputStream);
                string uzanti = (Guid.NewGuid().ToString() + fileinfo.Extension).ToLower();
                //img.Resize(225, 180, false, false);
                string tamyol = "~/Resim/" + uzanti;
                img.Save(Server.MapPath(tamyol));
                b.Banner = "/Resim/" + uzanti;

            }

            var deger = dr.BlokSayfas.Find(b.id);

            deger.Slogan = b.Slogan;

            if (b.Banner != null)
            {
                deger.Banner = b.Banner;
            }

            dr.SaveChanges();
            return RedirectToAction("AdmBlogBannerResim");

        }










        /////////////////////////////////---------------------------------------------- Galeri içerik
        /////

MobilyaProje/Views/KPanel/AdiminHakYazi.cshtml
@using MobilyaProje.Models
@model List<Hakkimizda>
@{
    ViewBag.Title = "AdiminHakYazi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div style="width:100%" ; class="col-md-12 table table-hover">
    @*<h2 style="color:red;">Dikkat! Veriler silindikten sonra Extra veri ekleyemezsiniz, Bu yüzden verileri GÜNCELLE yöntemini tercih ediniz!</h2>*@
    <h3>Hakkımda (Yazıları)</h3>
    <table class="table table-bordered">
        <tr>
            <th>Slogan</th>
            <th>Banner(Üst Resim)</th>
            <th>Başlık</th>
            <th>Resim</th>
            <th>Güncelle</th>
        </tr>
        @foreach (var x in Model)
        {
            <tr>

                @if (!String.IsNullOrEmpty(x.Slogan))
                {
                    <td>@x.Slogan</td>
                }
                else
                {
                    <td>Belirtilmemiş</td>
                }

                @if (!String.IsNullOrEmpty(x.Banner))
                {
                    <td>
                        <img src="@x.Banner" width="90px;" />
                    </td>
                }
                else
                {
                    <td>Belirtilmemiş</td>
                }

                @if (!String.IsNullOrEmpty(x.Baslik))
                {
                    <td>@x.Baslik</td>
                }
                else
                {
                    <td>Belirtilmemiş</td>
                }

                @if (!String.IsNullOrEmpty(x.Resim))
                {
                    <td>
                        <img src="@x.Resim" width="100px;" />

                    </td>
                }
                else
                {
                    <td>Belirtilmemiş</td>
                }


                <td><a href="~/KPanel/AdminHakGetir/@x.id" class="button border with-icon">Güncelle</a></td>
            </tr>
        }
    </table>

    <a href="~/Kpanel/HakkimizdaEkle/" class="btn btn-default">Yeni Hakkımızda</a>


</div>

MobilyaProje/Views/KPanel/AdmHGaleriicerikEkle.cshtml
@model MobilyaProje.Models.Galeriicerik
@{
    ViewBag.Title = "AdmHGaleriicerikEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>Galeri İçerik Ekle</h2>
<div class="col-md-12">
    @using (Html.BeginForm("AdmHGaleriicerikEkle", "KPanel", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <form class="form-group" method="post">

        <br />
        Başlık
        @Html.TextBoxFor(x => x.Baslik, new { @class = "form-control" })

        <br />
        Alt Başlık
        @Html.TextBoxFor(x => x.AltBaslik, new { @class = "form-control" })

        <br />
        Tarih
        @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
        <br />
        Konum
        @Html.TextBoxFor(x => x.Konum, new { @class = "form-control" })
        <br />
        Deger
        @Html.TextBoxFor(x => x.Deger, new { @class = "form-control" })
        <br />
        Müşteri
        @Html.TextBoxFor(x => x.Musteri, new { @class = "form-control" })
        <br />
        Kategori
        @Html.TextBoxFor(x => x.Kategori, new { @class = "form-control" })
        <br />
        İçerik
        <textarea name="icerik" cols="40" rows="3" class="form-control"></textarea>
        <br />
        İçerik2
        <textarea name="icerik1" cols="40" rows="3" class="form-control"></textarea>

        <br />
        Resim
        <input type="file" id="File" name="File" accept=".jpg,.JPG,.PNG,.png,.jpeg,.JPEG" class="form-control" />
        <br />

        @Html.HiddenFor(x => x.id)

        <button class="button border with-icon">Yeni İçerik Ekle</button>

    </form>
    }
</div>

MobilyaProje/Views/KPanel/AdmMesjGetr.cshtml
@model MobilyaProje.Models.Mesaj
@{
    ViewBag.Title = "AdmMesjGetr";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>İletişim Mesaj Sayfasını Güncelle</h3>

@using (Html.BeginForm("AdmMesjGuncelle", "KPanel", FormMethod.Post))
{
    <div id="div-boyut">

        @*<div>
            <label><b>Ad Soyad</b></label>
            @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
        </div>
        <div>
            <label><b>E-Posta</b></label>
            @Html.TextBoxFor(x => x.Eposta, new { @class = "form-control" })
        </div>

        <div>
            <label><b>Konu</b></label>
            @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
        </div>*@
        <div>
            <label><b>Mesaj</b></label>
            @Html.TextAreaFor(x => x.Mesajicerik, 3, 0, new { @class = "form-control" })
        </div>

        <div>
            @Html.HiddenFor(x => x.id)
        </div>
        <div>
            <button class="button border with-icon">Değişiklikleri Kaydet</button>
            <br />
            <br />
        </div>
    </div>


}

MobilyaProje/Views/KPanel/AdmNeYapiyoruzEkle.cshtml
@model MobilyaProje.Models.NeYapiyoruz
@{
    ViewBag.Title = "AdmNeYapiyoruzEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<h3>Yeni Hizmet Ekle</h3>


<div class="col-md-12" id="div-boyut">
    @using (Html.BeginForm("AdmNeYapiyoruzEkle", "KPanel", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <form method="post">
        @*<div>
            <label><b>Başlık</b></label>
            @Html.TextBoxFor(x => x.Baslik, new { @class = "form-control" })
        </div>*@
        <div>
            <label><b>Başlık</b></label>
            @Html.TextBoxFor(x => x.Baslik1, new { @class = "form-control" })
        </div>
        <div>
            <label><b>İçerik</b></label>
            @Html.TextAreaFor(x => x.icerik, 3, 0, new { @class = "form-control" })
        </div>
        <div>
            <label><b>Resim</b></label>
            <input type="file" id="File" name="File" accept=".jpg,.JPG,.PNG,.png,.jpeg,.JPEG" class="form-control" />
        </div>
        <div>
            <label><b>Resim Detay</b></label>
            <input type="file" id="File1" name="File1" accept=".jpg,.JPG,.PNG,.png,.jpeg,.JPEG" class="form-control" />
        </div>
        @*@Html.HiddenFor(x => x.id)*@

        <div>
            <button class="button border with-icon">Hizmeti Ekle</button>
        </div>
        <br />
    </form>
    }
</div>

MobilyaProje/Views/KPanel/AdmRefGetr.cshtml
@model MobilyaProje.Models.Referans
@{
    ViewBag.Title = "AdmRefGetr";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>Referanslar Sayfasını Güncelle</h3>

@using (Html.BeginForm("AdmRefGuncelle", "KPanel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div id="div-boyut">
        <div>
            <label><b>Resim</b></label>
            <input type="file" id="File" name="File" accept=".jpg,.JPG,.PNG,.png,.jpeg,.JPEG" class="form-control" />
        </div>


        <div>
            @Html.HiddenFor(x => x.id)
        </div>
        <div>
            <button class="button border with-icon">Değişiklikleri Kaydet</button>
            <br />
            <br />
        </div>
    </div>

}

MobilyaProje/Views/KPanel/AdmSurecimizGetr.cshtml
@model MobilyaProje.Models.Surecimiz
@{
    ViewBag.Title = "AdmSurecimizGetr";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>Sürecimiz Sayfasını Güncelle</h3>

@using (Html.BeginForm("AdmSurecimizGuncelle", "KPanel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div id="div-boyut">
        <label><b>Süreç Başlık</b></label>
        @Html.TextBoxFor(x => x.Surec, new { @class = "form-control" })
    </div>
    <div>
        <label><b>İçerik</b></label>
        @Html.TextAreaFor(x => x.icerik, 0, 4, new { @class = "form-control" })

    </div>

    <div>
        <label><b>Süreç Başlık2</b></label>
        @Html.TextBoxFor(x => x.Surec1, new { @class = "form-control" })

    </div>
    <div>
        <label><b>İçerik2</b></label>
        @Html.TextAreaFor(x => x.icerik1, 0, 4, new { @class = "form-control" })

    </div>
    <div>
        <label><b>Süreç Başlık3</b></label>
        @Html.TextBoxFor(x => x.Surec2, new { @class = "form-control" })

    </div>

    <div>
        <label><b>İçerik3</b></label>
        @Html.TextAreaFor(x => x.iceri2, 0, 2, new { @class = "form-control" })

    </div>

    <div>
        <label><b>Süreç Başlık4</b></label>
        @Html.TextBoxFor(x => x.Surec3, new { @class = "form-control" })

    </div>


    <div>
        <label><b>İçerik4</b></label>
        @Html.TextAreaFor(x => x.icerik3, 0, 4, new { @class = "form-control" })

    </div>


    <div>
        @Html.HiddenFor(x => x.id)
    </div>
    <div>
        <button class="button border with-icon">Değişiklikleri Kaydet</button>
        <br />
        <br />
    </div>


}

MobilyaProje/Views/KPanel/AdmiletsmGMesaj.cshtml
@using MobilyaProje.Models
@model List<Mesaj>
@{
    ViewBag.Title = "AdmiletsmGMesaj";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



@using (Html.BeginForm("AdmiletsmGMesaj", "KPanel", FormMethod.Post))
{
    <div class="col-md-12" style="float:left">
        <div class="col-md-6">
            <input type="text" name="p" placeholder="E Posta İle Arama Yap..." class="form-control" />

        </div>
        <div class="col-md-6">
            <input type="submit" class="button border with-icon" value="Ara..." />

        </div>

    </div>
    @*@Html.TextBox("p")*@

}

<div style="width:100%" ; class="col-md-12 table table-hover">
    <h3>İletişim Mesaj</h3>
    <table class="table table-bordered">
        <tr>
            <th>Ad Soyad</th>
            <th>E-Posta</th>
            <th>Telefon</th>
            <th>Mesaj İçerigi</th>
            <th>Tarih</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.AdSoyad</td>
                <td>@x.Eposta</td>
                <td>@x.Telefon</td>
                <td>@x.Mesajicerik</td>
                <td>@x.Tarih</td>
                @*<td>@x.Resim</td>*@
                <td><a href="~/KPanel/AdmMesjSil/@x.id" onclick="return confirm('Bunu Silmek İstediginizden Emin misin? @x.AdSoyad ')" class="button border with-icon" style="background-color:#ff0000; color:#fff">Sil</a></td>

                <td><a href="~/KPanel/AdmMesjGetr/@x.id" class="button border with-icon">Güncelle</a></td>
            </tr>
        }
    </table>

</div>

MobilyaProje/Views/KPanel/AdmiltGetr.cshtml
@model MobilyaProje.Models.iletisim
@{
    ViewBag.Title = "AdmiltGetr";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3> İletişim Sayfasını Güncelle</h3>

@using (Html.BeginForm("AdmiltGuncelle", "KPanel", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div id="div-boyut">

        <div>
            <label><b>Slogan</b></label>
            @Html.TextBoxFor(x => x.Slogan, new { @class = "form-control" })
        </div>
        <div>
            <label><b>Hatita</b></label>
            @Html.TextBoxFor(x => x.Maps, new { @class = "form-control" })
        </div>
        <div>
            <label><b>Mesaj Slogan</b></label>
            @Html.TextBoxFor(x => x.MesajSlogan, new { @class = "form-control" })
        </div>

        <div>
            <label><b>İletişim Başlık</b></label>
            @Html.TextBoxFor(x => x.iletisimBaslik, new { @class = "form-control" })
        </div>
        <div>
            <label><b>Resim</b></label>

            <input type="file" name="Banner" />
        </div>
        <div>
            <label><b>Adres</b></label>
            @Html.TextBoxFor(x => x.Adres, new { @class = "form-control" })
        </div>
        <div>
            <label><b>Telefon</b></label>
            @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
        </div>

        <div>
            <label><b>E Posta</b></label>
            @Html.TextBoxFor(x => x.Eposta, new { @class = "form-control" })
        </div>

        <div>
            <label><b>Web Site Adres</b></label>
            @Html.TextBoxFor(x => x.web, new { @class = "form-control" })
        </div>

        <div>
            <label><b>Çalışma Saatleri</b></label>
            @Html.TextBoxFor(x => x.CalismaSaatleri, new { @class = "form-control" })
        </div>

        <div>
            <label><b>Facebook</b></label>
            @Html.TextBoxFor(x => x.Fecbook, new { @class = "form-control" })
        </div>

        <div>
            <label><b>İnstegram</b></label>
            @Html.TextBoxFor(x => x.instegram, new { @class = "form-control" })
        </div>

        <div>
            <label><b>YouTube</b></label>
            @Html.TextBoxFor(x => x.Youtube, new { @class = "form-control" })
        </div>


        @Html.HiddenFor(x=>x.id)

        <div>
            <button class="button border with-icon">Değişiklikleri Kaydet</button>
            <br />
            <br />
        </div>
    </div>


}

MobilyaProje/Views/KPanel/AdminHiFormGetir.cshtml
@model MobilyaProje.Models.FormGonder
@{
    ViewBag.Title = "AdminHiFormGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>Müşteri Talep Formu Güncelle</h3>

@using (Html.BeginForm("AdmHizFormGuncel", "KPanel", FormMethod.Post))
{
    <div id="yazdir">
        <div @*id="div-boyut"*@>
            <label><b>Ad Soyad</b></label>
            @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
        </div>
        <div>
            <label><b>E-Posta</b></label>
            @Html.TextBoxFor(x => x.EPosta, new { @class = "form-control" })
        </div>
        <div>
            <label><b>Tel No</b></label>
            @Html.TextBoxFor(x => x.TelNo, new { @class = "form-control" })
        </div>
        <div>
            <label><b>Proje Başlıgı</b></label>
            @Html.TextBoxFor(x => x.ProjeBaslik, new { @class = "form-control" })
        </div>


        @*<label><b>Kategori</b></label>
            @Html.DropDownListFor(x => x.Kategoriid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })*@

        <label><b>Hizmet</b></label>
        @Html.DropDownListFor(x => x.Hizmetid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })

        <div>
            <label><b>Mesaj</b></label>
            @Html.TextAreaFor(x => x.ileti, 4, 0, new { @class = "form-control" })
        </div>
    </div>
    <div>
        @Html.HiddenFor(x => x.id)
    </div>
    <div>
        <button class="button border with-icon">Değişiklikleri Kaydet</button>
        <a href="javascript:;" onclick="printDiv('yazdir')" style="float:right;" class="btn btn-danger">PDF AL</a>
        <br />
        <br />
    </div>



}





<script>
    function printDiv(divName) {
        var printContents = document.getElementById(divName).innerHTML;
        var originalContents = document.body.innerHTML;
        document.body.innerHTML = printContents;
        window.print();
        document.body.innerHTML = originalContents;
    }
</script>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>


<script>
    $(document).ready(function () {
        var table = $('=example').DataTable({
            lengthChange: false,
            buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']
        });

        table.buttons().container()
            .appendTo('=example_wrapper .col-md-6:eq(0)');
    });
</script>